FROM rust:bullseye as builder
WORKDIR /app
COPY . .
RUN cargo build --release --bin prep

FROM debian:bullseye
RUN apt-get update && rm -rf /var/lib/apt/lists/*
RUN mkdir src
COPY --from=builder /app/src/web /src/web
COPY --from=builder /app/target/release/prep /usr/local/bin/prep
CMD ["prep"]