version: "3.8"

services:
  database:
    build: ./database
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
    ports:
      - ${DB_PORT}:${DB_PORT}
    # volumes:
    #   - ./data:/data

  web:
    build: .
    hostname: web
    ports:
      - ${APP_PORT}:${APP_PORT}
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
    depends_on:
      - database

  nginx:
    build: ./proxy
    ports:
      - ${NGINX_PORT}:${NGINX_PORT}
    depends_on:
      - web
      - database
