CREATE TABLE meal_plans (
    row_id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    meal_plan_id CHAR(36) UNIQUE NOT NULL,
    user_id CHAR(36) NOT NULL,
    meal_plan_name VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE meal_plans_to_recipes (
    row_id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    meal_plan_id CHAR(36) NOT NULL,
    recipe_id CHAR(36) NOT NULL
)